resources:
- name: bucket
  type: gcp-types/storage-v1:buckets
  properties:
    name: {{ properties["name"] }}
    location: {{ properties.get("location", "us-central1") }}
    storageClass: {{ properties.get("storageClass", "STANDARD") }}
    versioning:
      enabled: {{ properties.get("versioning", false) }}
    lifecycle:
      rule:
      - action:
          type: Delete
        condition:
          age: 30  # Delete cache entries older than 30 days
          
outputs:
- name: name
  value: $(ref.bucket.name)
- name: url
  value: gs://$(ref.bucket.name)