resources:
- name: job
  type: gcp-types/cloudscheduler-v1:projects.locations.jobs
  properties:
    parent: projects/{{ env["project"] }}/locations/us-central1
    name: {{ properties["name"] }}
    schedule: {{ properties["schedule"] }}
    timeZone: {{ properties.get("timezone", "UTC") }}
    httpTarget:
      uri: {{ properties["targetFunction"] }}
      httpMethod: POST
      headers:
        Content-Type: application/json
      body: {{ (properties.get("payload", {}) | jsonify | b64encode) }}
    retryConfig:
      retryCount: {{ properties.get("retryCount", 3) }}
      maxRetryDuration: 300s
      minBackoffDuration: 5s
      maxBackoffDuration: 3600s
      maxDoublings: 16
      
outputs:
- name: name
  value: $(ref.job.name)