resources:
- name: job
  type: gcp-types/cloudscheduler-v1:projects.locations.jobs
  properties:
    parent: projects/{{ env["project"] }}/locations/asia-northeast1
    name: {{ properties["name"] }}
    schedule: {{ properties["schedule"] }}
    timeZone: {{ properties.get("timezone", "UTC") }}
    httpTarget:
      uri: {{ properties["targetFunction"] }}
      httpMethod: POST
      headers:
        Content-Type: application/json
        Authorization: Bearer $(ref.webhook-auth-token-secret.secretValue)
      body: {{ (properties.get("payload", {}) | jsonify | b64encode) }}
    retryConfig:
      retryCount: {{ properties.get("retryCount", 1) }}
      maxRetryDuration: 300s
      minBackoffDuration: 5s
      maxBackoffDuration: 3600s
      maxDoublings: 16

# Secret Manager から webhook auth token を取得
- name: webhook-auth-token-secret
  type: gcp-types/secretmanager-v1:projects.secrets.versions.access
  properties:
    name: projects/{{ env["project"] }}/secrets/webhook-auth-token/versions/latest
      
outputs:
- name: name
  value: $(ref.job.name)