resources:
- name: function
  type: gcp-types/cloudfunctions-v1:projects.locations.functions
  properties:
    location: projects/{{ env["project"] }}/locations/{{ properties["location"] }}
    function: {{ properties["name"] }}
    sourceArchiveUrl: gs://{{ env["project"] }}-function-source/{{ properties["name"] }}.zip
    entryPoint: {{ properties["entryPoint"] }}
    runtime: {{ properties["runtime"] }}
    httpsTrigger: {}
    availableMemoryMb: {{ properties.get("memory", 512) }}
    timeout: {{ properties.get("timeout", "540s") }}
    secretEnvironmentVariables:
    - key: GEMINI_API_KEY
      projectId: {{ env["project"] }}
      secret: gemini-api-key
      version: latest
    - key: SLACK_BOT_TOKEN
      projectId: {{ env["project"] }}
      secret: slack-bot-token
      version: latest
    - key: WEBHOOK_AUTH_TOKEN
      projectId: {{ env["project"] }}
      secret: webhook-auth-token
      version: latest
    serviceAccountEmail: {{ properties.get("serviceAccount", "default") }}
    
- name: function-invoker
  type: gcp-types/cloudfunctions-v1:projects.locations.functions.setIamPolicy
  properties:
    resource: $(ref.function.name)
    policy:
      bindings:
      - role: roles/cloudfunctions.invoker
        members:
        - allUsers
        
outputs:
- name: httpsUrl
  value: $(ref.function.httpsTrigger.url)
- name: name
  value: $(ref.function.name)