imports:
- path: cloud-function.yaml
- path: cloud-scheduler.yaml
- path: cloud-storage.yaml

resources:
# Storage bucket for cache
- name: article-summarizer-cache
  type: cloud-storage.yaml
  properties:
    name: article-summarizer-processed-articles
    location: asia-northeast1

# Cloud Function
- name: article-summarizer-function
  type: cloud-function.yaml
  properties:
    name: article-summarizer-v3
    location: us-central1
    runtime: go121
    entryPoint: ProcessRSSScheduled
    topicName: article-summarizer-trigger
    memory: 512
    timeout: 540s
    environmentVariables:
      CACHE_BUCKET: $(ref.article-summarizer-cache.name)
      GEMINI_API_KEY: "YOUR_GEMINI_API_KEY"
      SLACK_BOT_TOKEN: "YOUR_SLACK_BOT_TOKEN"
      WEBHOOK_AUTH_TOKEN: "YOUR_WEBHOOK_AUTH_TOKEN"

# Pub/Sub topic for function triggers
- name: article-summarizer-topic
  type: gcp-types/pubsub-v1:projects.topics
  properties:
    topic: article-summarizer-trigger

# Scheduler jobs
- name: rss-scheduler-hatena
  type: cloud-scheduler.yaml
  properties:
    name: rss-scheduler-hatena
    schedule: "0 */3 * * *"  # Every 3 hours
    topicName: $(ref.article-summarizer-topic.name)
    payload:
      feedName: hatena
      
- name: rss-scheduler-lobsters
  type: cloud-scheduler.yaml
  properties:
    name: rss-scheduler-lobsters
    schedule: "30 */4 * * *"  # Every 4 hours, offset by 30 minutes
    topicName: $(ref.article-summarizer-topic.name)
    payload:
      feedName: lobsters