imports:
- path: cloud-function.yaml
- path: cloud-scheduler.yaml
- path: cloud-storage.yaml

resources:
# Storage bucket for cache
- name: article-summarizer-cache
  type: cloud-storage.yaml
  properties:
    name: article-summarizer-processed-articles
    location: asia-northeast1

# Service Account for Function
- name: function-service-account
  type: gcp-types/iam-v1:projects.serviceAccounts
  properties:
    accountId: article-summarizer-sa
    serviceAccount:
      displayName: Article Summarizer Service Account

# Secret Manager権限付与
- name: secret-accessor-binding
  type: gcp-types/cloudresourcemanager-v1:virtual.projects.iamMemberBinding
  properties:
    resource: gen-lang-client-0715048106
    role: roles/secretmanager.secretAccessor
    member: serviceAccount:article-summarizer-sa@gen-lang-client-0715048106.iam.gserviceaccount.com
  metadata:
    dependsOn:
    - function-service-account

# Cloud Function
- name: article-summarizer-function
  type: cloud-function.yaml
  properties:
    name: article-summarizer-v3
    location: asia-northeast1
    runtime: go121
    entryPoint: SummarizeArticles
    memory: 512
    timeout: 540s
    serviceAccount: article-summarizer-sa@gen-lang-client-0715048106.iam.gserviceaccount.com
  metadata:
    dependsOn:
    - article-summarizer-cache
    - secret-accessor-binding

# Scheduler jobs
- name: rss-scheduler-hatena
  type: cloud-scheduler.yaml
  properties:
    name: rss-scheduler-hatena
    schedule: "0 */3 * * *"  # Every 3 hours
    targetFunction: $(ref.article-summarizer-function.httpsUrl)
    feedName: hatena
    authToken: {{ properties["webhookAuthToken"] }}
    payload:
      feedName: hatena
      
- name: rss-scheduler-lobsters
  type: cloud-scheduler.yaml
  properties:
    name: rss-scheduler-lobsters
    schedule: "30 */4 * * *"  # Every 4 hours, offset by 30 minutes
    targetFunction: $(ref.article-summarizer-function.httpsUrl)
    feedName: lobsters
    authToken: {{ properties["webhookAuthToken"] }}
    payload:
      feedName: lobsters
