imports:
- path: cloud-function.yaml
- path: cloud-scheduler.yaml
- path: cloud-storage.yaml

resources:
# Storage bucket for cache
- name: article-summarizer-cache
  type: cloud-storage.yaml
  properties:
    name: article-summarizer-processed-articles
    location: asia-northeast1

# Cloud Function
- name: article-summarizer-function
  type: cloud-function.yaml
  properties:
    name: article-summarizer-v3
    location: asia-northeast1
    runtime: go121
    entryPoint: SummarizeArticles
    topicName: article-summarizer-trigger
    memory: 512
    timeout: 540s
    environmentVariables:
      CACHE_BUCKET: $(ref.article-summarizer-cache.name)
      GEMINI_API_KEY: {{ properties["geminiApiKey"] }}
      SLACK_BOT_TOKEN: {{ properties["slackBotToken"] }}
      WEBHOOK_AUTH_TOKEN: {{ properties["webhookAuthToken"] }}

# Scheduler jobs
- name: rss-scheduler-hatena
  type: cloud-scheduler.yaml
  properties:
    name: rss-scheduler-hatena
    schedule: "0 */3 * * *"  # Every 3 hours
    targetFunction: $(ref.article-summarizer-function.httpsUrl)
    feedName: hatena
    authToken: {{ properties["webhookAuthToken"] }}
    payload:
      feedName: hatena
      
- name: rss-scheduler-lobsters
  type: cloud-scheduler.yaml
  properties:
    name: rss-scheduler-lobsters
    schedule: "30 */4 * * *"  # Every 4 hours, offset by 30 minutes
    targetFunction: $(ref.article-summarizer-function.httpsUrl)
    feedName: lobsters
    authToken: {{ properties["webhookAuthToken"] }}
    payload:
      feedName: lobsters